# Generated by Django 3.2.10 on 2021-12-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.ImageField(blank=True, upload_to='games/'),
        ),
    ]
